wallpaper {
    monitor = DP-3
    path = /home/nickg/Pictures/Wallpapers/turtle1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/nickg/Pictures/Wallpapers/turtle2.jpg
    fit_mode = cover
}
