wallpaper {
    monitor = DP-3
    path = /home/nickg/Pictures/Wallpapers/02.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/nickg/Pictures/Wallpapers/03.jpg
    fit_mode = cover
}
